export default function Head() {
	return (
		<>
			<title>Bulma 2</title>
			<meta
				content="width=device-width, initial-scale=1"
				name="viewport"
			/>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			<link
				href="https://pro.fontawesome.com/releases/v5.15.1/css/all.css"
				rel="stylesheet"
				precedence="default"
			></link>
		</>
	);
}
